from together import Together

general_prompt = ""
target_prompt = ""

# Чтение первого файла
with open('prompts/general.txt', 'r', encoding='utf-8') as file:
    general_prompt = file.read()

# Чтение второго файла
with open('prompts/reinhard.txt', 'r', encoding='utf-8') as file:
    target_prompt = file.read()

user_input = "Сепарабельное размытие изображения по Гауссу"; # input("Что будем программировать? ")

client = Together(api_key="") # auth defaults to os.environ.get("TOGETHER_API_KEY")

messages = [
        {"role": "system", 
        "content": "Ты — AI помошник по параллельному программированию на С++ при помощи технологии kernel_slicer. Context: " + general_prompt + "\n" + target_prompt},
        {"role": "user", "content":  "Напиши программу " + user_input + " с использованием kernel_slicer"},
        {"role": "user", "content" : '''перенеси все вектора, объявленные в функция-членах класса в сам класс. Сделай их членами класса.
                                        Все такие вектора должны быть зарезервированы в конструкторе класса на заразее заданный, передаваемый через конструктор размер.
                                        Покажи как использовать полученный класс with the generated by kernel_slicer code'''}
    ]

print("first time ... ")
response = client.chat.completions.create(
    model = "deepseek-ai/DeepSeek-V3",
    messages = messages
)

print("choices.size() = ", len(response.choices))
reply = response.choices[0].message.content
with open('reply.md', 'w', encoding='utf-8') as file:
    file.write(reply)

print("Finished. Please see reply in 'reply.md'")
